In [1]:
def twoSum(num1: int, num2: int=100) -> int:
    sum = num1 + num2
    return sum  

if __name__ == "__main__":
    print(twoSum.__annotations__)
    print(twoSum(1,2))
    print(twoSum(1))
    print(twoSum('I love ','Arsenal'))

{'num1': <class 'int'>, 'num2': <class 'int'>, 'return': <class 'int'>}
3
101
I love Arsenal


In [28]:
transition_matrix = np.matrix([[0.8, 0.2],
                    [0.4, 0.6]], dtype=float)
print("转移矩阵: \n", transition_matrix)

print('\n')
transition_matrix_T = np.transpose(transition_matrix)
print("转移矩阵转置: \n", transition_matrix_T)

print('\n')
print("特征值: \n", np.linalg.eig(transition_matrix_T)[0])

print('\n')
print("特征向量: \n", np.linalg.eig(transition_matrix_T)[1])

print('\n')
print("第一个特征值对应的特征向量: \n", np.linalg.eig(transition_matrix_T)[1][:,0])

转移矩阵: 
 [[0.8 0.2]
 [0.4 0.6]]


转移矩阵转置: 
 [[0.8 0.4]
 [0.2 0.6]]


特征值: 
 [1.  0.4]


特征向量: 
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


第一个特征值对应的特征向量: 
 [[0.89442719]
 [0.4472136 ]]


In [14]:
class father:
    def __init__(self, father_attribute = "father"):
        self.father_attribute = father_attribute

class child_without_ini(father):
    pass

class child_with_ini(father):
    def __init__(self, child_attribute):
        self.child_attribute = child_attribute

class child_with_super(father):
    def __init__(self,father_attribute, child_attribute):
        self.child_attribute = child_attribute
        super().__init__(father_attribute)

test_class_without_ini = child_without_ini()
test_class_with_ini = child_with_ini('child')
test_class_with_super = child_with_super('child_father', 'child')


#linus 自动继承父类所有的属性
print("test_class_without_ini:")
print(test_class_without_ini.father_attribute, "\n")

#linus 不仅仅有父类属性，还有子类的属性
print("test_class_with_super:")
print(test_class_with_super.father_attribute)
print(test_class_with_super.child_attribute, "\n")

#linus 父类的初始化函数被覆盖
print("test_class_with_ini:")
print(test_class_with_ini.child_attribute)
print(test_class_with_ini.father_attribute)




test_class_without_ini:
father 

test_class_with_super:
child_father
child 

test_class_with_ini:
child


AttributeError: 'child_with_ini' object has no attribute 'father_attribute'