In [1]:
def twoSum(num1: int, num2: int=100) -> int:
    sum = num1 + num2
    return sum  

if __name__ == "__main__":
    print(twoSum.__annotations__)
    print(twoSum(1,2))
    print(twoSum(1))
    print(twoSum('I love ','Arsenal'))

{'num1': <class 'int'>, 'num2': <class 'int'>, 'return': <class 'int'>}
3
101
I love Arsenal


In [11]:
with open('./text', 'w') as fo:
    print('hello') 

In [28]:
transition_matrix = np.matrix([[0.8, 0.2],
                    [0.4, 0.6]], dtype=float)
print("转移矩阵: \n", transition_matrix)

print('\n')
transition_matrix_T = np.transpose(transition_matrix)
print("转移矩阵转置: \n", transition_matrix_T)

print('\n')
print("特征值: \n", np.linalg.eig(transition_matrix_T)[0])

print('\n')
print("特征向量: \n", np.linalg.eig(transition_matrix_T)[1])

print('\n')
print("第一个特征值对应的特征向量: \n", np.linalg.eig(transition_matrix_T)[1][:,0])

转移矩阵: 
 [[0.8 0.2]
 [0.4 0.6]]


转移矩阵转置: 
 [[0.8 0.4]
 [0.2 0.6]]


特征值: 
 [1.  0.4]


特征向量: 
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


第一个特征值对应的特征向量: 
 [[0.89442719]
 [0.4472136 ]]


In [14]:
class father:
    def __init__(self, father_attribute = "father"):
        self.father_attribute = father_attribute

class child_without_ini(father):
    pass

class child_with_ini(father):
    def __init__(self, child_attribute):
        self.child_attribute = child_attribute

class child_with_super(father):
    def __init__(self,father_attribute, child_attribute):
        self.child_attribute = child_attribute
        super().__init__(father_attribute)

test_class_without_ini = child_without_ini()
test_class_with_ini = child_with_ini('child')
test_class_with_super = child_with_super('child_father', 'child')


#linus 自动继承父类所有的属性
print("test_class_without_ini:")
print(test_class_without_ini.father_attribute, "\n")

#linus 不仅仅有父类属性，还有子类的属性
print("test_class_with_super:")
print(test_class_with_super.father_attribute)
print(test_class_with_super.child_attribute, "\n")

#linus 父类的初始化函数被覆盖
print("test_class_with_ini:")
print(test_class_with_ini.child_attribute)
print(test_class_with_ini.father_attribute)

#linsu 深度思考
'''
每个类的函数都保存在内存的一个地方，有一个指针可以定位。
当类初始化的时候，就会通过对应的指针调用对应的__init__()函数。
当类调用某一个函数的时候，也会通过对应的指针调用对应的函数。

当继承的时候，子类可以用的指针就包括父类的所有函数指针和子类所有的函数指针。
如果子类和函数和父类函数的函数名重命了，就会调用子类的函数。
如果在重命的情况下，有没有办法仍然调用父类的函数呢？有，通过super().funname()
'''

test_class_without_ini:
father 

test_class_with_super:
child_father
child 

test_class_with_ini:
child


AttributeError: 'child_with_ini' object has no attribute 'father_attribute'

In [9]:
#linus 非常漂亮的一个🌰
class father:
    def __init__(self, father_attribute = "father"):
        self.father_attribute = father_attribute
    
    def get_name(self):
        return self.father_attribute

class child_with_ini(father):
    def __init__(self, child_attribute):
        self.child_attribute = child_attribute
        super().__init__()
    
    def get_name(self):
        return self.child_attribute + super().get_name()

test_class_with_ini = child_with_ini('child')
print(test_class_with_ini.child_attribute + test_class_with_ini.father_attribute)
print(test_class_with_ini.get_name())


childfather
childfather


In [3]:
from manim import *

state_color_map = {}
state_color_map[1] = RED
state_color_map[2] = BLUE
state_color_map[3] = GREEN
state_color_map[4] = YELLOW

Manim Community v0.16.0.post0

In [4]:
state_color_map

{1: '#FC6255', 2: '#58C4DD', 3: '#83C167', 4: '#FFFF00'}

In [5]:
print(state_color_map)

{1: '#FC6255', 2: '#58C4DD', 3: '#83C167', 4: '#FFFF00'}
